include:
  - component: singular-code.de/singularit/ci-components/deployment/deploy-docker-compose/deployment@1.12.0
    inputs:
      services: app,~postgres,~migration,~redis
      base_domain: v2.singular-it-test.de
      base_compose_file: .gitlab/docker-compose.staging.yml
      auto_stop_in: 6 months
