pytest:
  stage: test
  image: orbisk/django-test:3.11
  extends: .size:medium
  services:
    - postgres:{{ cookiecutter.postgresql_version }}
  variables:
    DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  before_script:
    - pip install -r requirements/local.txt
  script:
    - pytest
