stages:
  - lint
  - test
  - deploy

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
  - component: $CI_COMPONENTS_BASE_URL/utilities/size@~latest

variables:
  POSTGRES_USER: '{{ cookiecutter.project_slug }}'
  POSTGRES_PASSWORD: 'postgres'
  POSTGRES_DB: 'test_{{ cookiecutter.project_slug }}'
  POSTGRES_HOST_AUTH_METHOD: trust
  {%- if cookiecutter.use_celery == 'y' %}
  CELERY_BROKER_URL: 'redis://redis:6379/0'
  {%- endif %}
