version: "3.8"

services:
  migration:
    build:
        context: ..
        dockerfile: .gitlab/Dockerfile
        target: base
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DJANGO_ALLOWED_HOSTS=.singular-it-test.de
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_ADMIN_URL=.admin/
      - DJANGO_SECRET_KEY
      - REDIS_URL=$CELERY_BROKER_URL
      {%- if cookiecutter.use_celery == 'y' %}
      - CELERY_BROKER_URL
      {%- endif %}
    depends_on:
      postgres:
        condition: service_healthy

    command: ["python", "manage.py", "migrate"]
  app:
    extends:
      service: migration
    build:
      context: ..
      dockerfile: .gitlab/Dockerfile
      target: app
    restart: unless-stopped
    command: ["gunicorn", "-b", ":8000", "--workers=3", "--enable-stdio-inheritance", "config.wsgi:application"]
    expose:
      - 8000
  postgres:
    image: postgres:{{ cookiecutter.postgresql_version }}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
